name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Cache yarn
        uses: bahmutov/npm-install@v1.4.5
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Build project
        run: yarn build
      - name: Export static files
        run: yarn export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out